### ISSUE TITLE
web_1 | target: `http://${ctx.request.header.host?.split(':')[0]}:8080`,SyntaxError: Unexpected token .

### ISSUE THREAD

**Issue by kute** [vesoft-inc/nebula-web-docker#205]
v2，执行`docker-compose up -d`，其中`web`服务启动失败，具体如下

```
web_1 | /nebula-graph-studio/app/middleware/proxy.js:13

web_1 | target: `http://${ctx.request.header.host?.split(':')[0]}:8080`,

web_1 | ^

web_1 |

web_1 | SyntaxError: Unexpected token .

web_1 | at Module._compile (internal/modules/cjs/loader.js:723:23)

web_1 | at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

web_1 | at Module.load (internal/modules/cjs/loader.js:653:32)

web_1 | at tryModuleLoad (internal/modules/cjs/loader.js:593:12)

web_1 | at Function.Module._load (internal/modules/cjs/loader.js:585:3)

web_1 | at Module.require (internal/modules/cjs/loader.js:692:17)

web_1 | at require (internal/modules/cjs/helpers.js:25:18)

web_1 | at Object.loadFile (/nebula-graph-studio/node_modules/egg-core/lib/utils/index.js:27:19)

web_1 | at getExports (/nebula-graph-studio/node_modules/egg-core/lib/loader/file_loader.js:199:23)

web_1 | at FileLoader.parse (/nebula-graph-studio/node_modules/egg-core/lib/loader/file_loader.js:158:25)

web_1 | 2021-02-22 10:02:44,398 ERROR 29 [master] exit with code:1

web_1 | 2021-02-22 10:02:44,409 ERROR 36 [agent_worker] receive disconnect event on child_process fork mode, exiting with code:110

web_1 | 2021-02-22 10:02:44,414 ERROR 36 [agent_worker] exit with code:110

web_1 | 2021-02-22 10:02:44,413 INFO 36 [agent_worker] beforeExit success

web_1 | 2021-02-22 10:02:44,454 INFO 54 [egg:logger] init all loggers with options: {"dir":"/root/logs/nebula-graph-studio","encoding":"utf8","env":"prod","level":"INFO","consoleLevel":"INFO","disableConsoleAfterReady":true,"outputJSON":false,"buffer":true,"appLogName":"nebula-graph-studio-web.log","coreLogName":"egg-web.log","agentLogName":"egg-agent.log","errorLogName":"common-error.log","coreLogger":{},"allowDebugAtProd":false,"type":"application"}

web_1 | 2021-02-22 10:02:44,459 INFO 60 [egg:logger] init all loggers with options: {"dir":"/root/logs/nebula-graph-studio","encoding":"utf8","env":"prod","level":"INFO","consoleLevel":"INFO","disableConsoleAfterReady":true,"outputJSON":false,"buffer":true,"appLogName":"nebula-graph-studio-web.log","coreLogName":"egg-web.log","agentLogName":"egg-agent.log","errorLogName":"common-error.log","coreLogger":{},"allowDebugAtProd":false,"type":"application"}

web_1 | npm ERR! code ELIFECYCLE

web_1 | npm ERR! errno 1

web_1 | npm ERR! nebula-graph-studio@2.1.6-beta docker-start: `egg-scripts start --title=egg-server-nebula-graph-studio`

web_1 | npm ERR! Exit status 1

web_1 | npm ERR!

web_1 | npm ERR! Failed at the nebula-graph-studio@2.1.6-beta docker-start script.

web_1 | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

web_1 |

web_1 | npm ERR! A complete log of this run can be found in:

web_1 | npm ERR! /root/.npm/_logs/2021-02-22T10_02_44_478Z-debug.log

v2_web_1 exited with code 1
```

**Comment by nianiaJR** [comment]
docker-compose pull 更新一下最新代码，这个已经修复啦
